// 1. 【核心對照表】定義哪個勢力擁有哪幾個主題
const categoryMap = {
    "POE流亡暗道": ["教學攻略", "流派收藏", "故事劇情", "二次創作", "藏身處", "休閒日常",],
    "☯東方Project": ["博麗神主ZUN", "原作", "二次創作", "東方Project音樂",],
    "藝術學院": ["劇本", "繪圖", "動畫", "3D", "攝影|影片|剪輯", "舞蹈|動作|武術", "樂理|配樂|音效",],
    "休閒牧場": ["休閒牧場", "ACG同好會", "Vtuber", "這是什麼酷酷的東西", "健身|養身", "體育運動", "棋類技藝", "風水|玄學|靈異|怪異",],
    "社會學院": ["社會學", "吹哨者", "台灣[Taiwan]",],
    "人生哲學": ["人生哲學", "戀愛研究院", "商學院",],
    "生活日常": ["生活日常", "裝扮造型風格", "飲食", "清潔打掃",],
    "音樂收藏": ["淺層", "中層", "深層", "臨界層", "凝界層", "音樂探討", "樂理八卦", "音樂資源", "東方Project音樂",],
    "程式語言": ["HTML", "CSS", "JavaScript", "python", "命令提示字元", "AutoHotkey",],
    "學術領域": ["醫學", "科學", "科技", "軍武", "工匠技藝", "建築學", "生物學", "軟體硬體應用", "泛科普教育",],
    "語言研究院": ["中文", "英文", "日文",],
    "遊戲製作": ["Godot", "Unity",],
    "系列主題": ["柯文哲-先行者", "黃國昌-通識課", "陳之漢-義士", "陳椒華-循道者",],
    "台灣民眾黨專區": ["台灣民眾黨專區", "街頭活動", "小草專區",],
    // 💡 如果有新增的勢力，依樣畫葫蘆加在下面即可
};

// 2. 【大全清單】當使用者選回「系列勢力（全部）」時，要秀出的所有主題
const allCategories = [
 " ",
];

const workData = [
    { date: '2019-01-03', path: '⛩︎', pathUrl: 'https://youtu.be/FJ58Dk_cJKA?si=-gTaufhDXPeLTDzo', area: ' 音樂收藏', category: ' 深層', title: "mein schatz", rarity: ' 傳奇', prefix: ' ', suffix: " MONOGATARI Series - 主題" },
    { date: '2017-03-21', path: '⛩︎', pathUrl: 'https://youtu.be/FTy-IKW7-cI?si=8xcB0Ha1WyYeZ5op', area: ' 音樂收藏/☯東方Project', category: ' 中層/東方Project音樂', title: "【東方】Bunkacho DS 〜 無間の鐘【ハウスリミックス】", rarity: ' 稀有', prefix: ' 純音樂', suffix: " Kuroneko Lounge" },
    { date: '2021-11-30', path: '⛩︎', pathUrl: 'https://youtu.be/fYA0rxcm7UA?si=1M8dhdWjWKC0PavH', area: ' 音樂收藏/☯東方Project', category: ' 中層/東方Project音樂', title: "【公式】勤労系女子　永江 衣玖/あらいぐまファクトリー（東方Vocalアレンジ　原曲：黒い海に紅く ～ Legendary Fish.）", rarity: ' 稀有', prefix: ' ', suffix: " あらいぐまファクトリー（Raccoon Factory）" },
    { date: '2019-11-03', path: '⛩︎', pathUrl: 'https://youtu.be/FyN_Hbe0Ov4?si=LwxrKnQdJl3WEvZ6', area: ' 音樂收藏/☯東方Project', category: ' 凝界層/東方Project音樂', title: "【Len'en Arrange】Forgotten in Dreams", rarity: ' 稀有', prefix: ' 純音樂', suffix: " LENK64" },
    { date: '2016-02-25', path: '⛩︎', pathUrl: 'https://youtu.be/gEMGeC4rTtw?si=RbJByrXAB2d2MVAF', area: ' 音樂收藏', category: ' 中層', title: "TheFatRat ft. Laura Brehm - Monody (Radio Edit)", rarity: ' 稀有', prefix: ' ', suffix: " PM Recordings" },
    { date: '2019-08-18', path: '⛩︎', pathUrl: 'https://youtu.be/cTVoiqPuwPU?si=w8psMp-XqXG3FVLt', area: ' 音樂收藏/東方Project音樂', category: ' 中層/東方Project音樂', title: "【 Vocal】Itori-Zytokine【Pleione】【Subbed-English-Spanish】", rarity: ' 稀有', prefix: ' ', suffix: " ¡AlChileSi!" },
    { date: '2015-09-19', path: '⛩︎', pathUrl: 'https://youtu.be/cxWJK8VJkoQ?si=LsCAinq5lEhCFnu8', area: ' 音樂收藏/東方Project音樂', category: ' 中層/東方Project音樂', title: "ᴴᴰ【東方Vocal】DiGiTAL WiNG｜Abracadabra【中日附詞】", rarity: ' 稀有', prefix: ' ', suffix: " 萌樂 ‧ Meng Yue ᴴᴰ" },
    { date: '2017-01-21', path: '⛩︎', pathUrl: 'https://youtu.be/cyjgw3uFn6s?si=NgYApfwzE9dAY3Tp', area: ' 音樂收藏/東方Project音樂', category: ' 深層/東方Project音樂', title: "東方 Touhou remix (Orchestral) Septette for a Dead Princess", rarity: ' 稀有', prefix: ' 純音樂', suffix: " Lowlands Blossom" },
    { date: '2017-10-22', path: '⛩︎', pathUrl: 'https://youtu.be/DpvzElVm-fQ?si=6HElqCiIDQUDuFFe', area: ' 音樂收藏', category: ' 凝界層', title: "MuseScore ★ 【ピアノ琴譜】犬夜叉 - 時代を越える想い / Inuyasha Theme - Affections Across Time Piano Sheet Music", rarity: ' 稀有', prefix: ' 純音樂', suffix: " Piano Room No.1 一號琴房 (Candy Tsai)" },
    { date: '2008-02-28', path: '⛩︎', pathUrl: 'https://youtu.be/Drb7-uEb9aA?si=zDgAxFEBSRIPdNRG', area: ' 音樂收藏/☯東方Project', category: ' 淺層/東方Project音樂', title: "東方VocalBGM _心の在り処_【原曲_ 人形裁判　～ 人の形弄びし少女 】", rarity: ' 稀有', prefix: ' ', suffix: " RYUGA626" },
    { date: '2018-12-23', path: '⛩︎', pathUrl: 'https://youtu.be/DtBoAqkIJzI?si=Jxl09u3HL576Lop4', area: ' 音樂收藏', category: ' 中層', title: "幽霊東京 / Ayase (self cover)", rarity: ' 一般', prefix: ' ', suffix: " YOASOBI和2" },
    { date: '2022-04-01', path: '⛩︎', pathUrl: 'https://youtu.be/DUMSWo70SwE?si=QchvoBCOWCgFmwzR', area: ' 音樂收藏', category: ' 淺層/中層', title: "Irreversible Demon | ENGLISH Cover by Milkychan", rarity: ' 魔法', prefix: ' ', suffix: " Milkychan" },
    { date: '2013-01-02', path: '⛩︎', pathUrl: 'https://youtu.be/E4n8Nodai-I?si=FvApAO9OxEmPkCsw', area: ' 音樂收藏/☯東方Project', category: ' 淺層/中層/東方Project音樂', title: "Alstroemeria Records - ORIENTAL MAGICIAN [HD]", rarity: ' 魔法', prefix: ' ', suffix: " SpaceDustDragon" },
    { date: '2013-11-07', path: '⛩︎', pathUrl: 'https://youtu.be/EczdC7_WxVQ?si=YokzbVIpdSCkMq4E', area: ' 音樂收藏', category: ' 中層', title: "RWBY Gold (Full with Lyrics)", rarity: ' 魔法', prefix: ' ', suffix: " animefancy ONE" },
    { date: '2014-05-11', path: '⛩︎', pathUrl: 'https://youtu.be/epkhQBZ0sHc?si=gkjQS1tpaQxxG-FO', area: ' 音樂收藏/☯東方Project', category: ' 中層/凝界層/東方Project音樂', title: "[東方 Rock/Vocal] [Diao ye zong] その正しき言葉のもとに", rarity: ' 魔法', prefix: ' ', suffix: " The Little Pagoda" },
    { date: '2018-05-24', path: '⛩︎', pathUrl: 'https://youtu.be/f0HSEc8sAJU?si=-ou1ricR3U1U1lHS', area: ' 音樂收藏/☯東方Project', category: ' 中層/凝界層/東方Project音樂', title: "【東方Vocal／Acoustic Ballad】 Bravy Girl 「ONSEN PROJECT」[ENG Subs]", rarity: ' 傳奇', prefix: ' ', suffix: " Kappashiro" },
    { date: '2021-07-14', path: '⛩︎', pathUrl: 'https://youtu.be/kHIu-nXWGaI?si=pWKCXOnjmQiWK3Wo', area: ' 音樂收藏', category: ' 中層', title: 'いのちの名前 - 木村弓 千と千尋の神隠し あの日の川', rarity: ' 稀有', prefix: ' ', suffix: " high_note Music Lounge" },
    { date: '2012-02-03', path: '⛩︎', pathUrl: 'https://youtu.be/CG_KZCb96NA?si=FClRGBVAyvdPTiFY', area: ' 音樂收藏', category: ' 中層', title: '【初音ミク】 ぼくらのレットイットビー 【オリジナルPV】 中文字幕嵌入', rarity: ' 魔法', prefix: ' ', suffix: " catLee" },
    { date: '2018-06-06', path: '⛩︎', pathUrl: 'https://youtu.be/CP662nLz-Ww?si=UdGWW43yflQvOh-P', area: ' 音樂收藏/東方Project', category: ' 中層/東方Project音樂', title: "【管弦樂】東方緋想天 - 砕月 / Touhou 10.5 - Broken Moon(Suika's Theme) Orchestral Ver.", rarity: ' 魔法', prefix: ' 純音樂', suffix: " Piano Room No.1 一號琴房 (Candy Tsai)" },
    { date: '2018-11-07', path: '⛩︎', pathUrl: 'https://youtu.be/dAW8QaZV_LY?si=nG_Y33R12MvdlY5R', area: ' 音樂收藏', category: ' 中層', title: '青春アミーゴ - 修二と彰', rarity: ' 魔法', prefix: ' ', suffix: " high_note Music Lounge" },
    { date: '2016-03-23', path: '⛩︎', pathUrl: 'https://youtu.be/p2bx9n-ybrU?si=IafBZ_ql7EZyrDh_', area: ' 音樂收藏', category: ' 中層/凝界層', title: 'secret base ～君がくれたもの～ ZONE（フル）', rarity: ' 稀有', prefix: ' ', suffix: " high_note Music Lounge" },
    { date: '2018-11-14', path: '⛩︎', pathUrl: 'https://youtu.be/iUopLywHk3E?si=1dVAdXBcLEosT3lk', area: ' 音樂收藏', category: ' 中層', title: 'Jupiter - 平原綾香（フル）', rarity: ' 魔法', prefix: ' ', suffix: " high_note Music Lounge" },
    { date: '2014-11-19', path: '⛩︎', pathUrl: 'https://youtu.be/AvdT8sYk2lk?si=TnR7aK1A2Wzq9WmV', area: ' 音樂收藏', category: ' 中層', title: 'ありがとう - いきものがかり（フル）', rarity: ' 魔法', prefix: ' ', suffix: " high_note Music Lounge" },
    { date: '2014-07-30', path: '⛩︎', pathUrl: 'https://youtu.be/2hACJAwT4ik?si=5cqfKYFBGqBJxDPx', area: ' 音樂收藏', category: ' 中層', title: '夜空ノムコウ - SMAP', rarity: ' 稀有', prefix: ' ', suffix: " high_note Music Lounge" },
    { date: '2016-03-09', path: '⛩︎', pathUrl: 'https://youtu.be/fQBsNmbXY98?si=ol_q-D1T6ONyabax', area: ' 音樂收藏', category: ' 中層', title: 'Best Friend - Kiroro（キロロ）（フル）', rarity: ' 稀有', prefix: ' ', suffix: " high_note Music Lounge" },
    { date: '2017-07-12', path: '⛩︎', pathUrl: 'https://youtu.be/3S5Yu9HpE3I?si=m_dGeTIP7jS9ZkEK', area: ' 音樂收藏', category: ' 淺層', title: '残酷な天使のテーゼ - 高橋洋子（フル）', rarity: ' 稀有', prefix: ' ', suffix: " high_note Music Lounge" },
    { date: '2019-01-23', path: '⛩︎', pathUrl: 'https://youtu.be/GSpdPn14lno?si=IYCVxCGjUjTp93CK', area: ' 音樂收藏', category: ' 淺層', title: '創聖のアクエリオン - AKINO（フル）', rarity: ' 魔法', prefix: ' ', suffix: " high_note Music Lounge" },
    { date: '2017-05-17', path: '⛩︎', pathUrl: 'https://youtu.be/Y9TL7VyS5NY?si=XnLNeH2-O3g4Yhf3', area: ' 音樂收藏', category: ' 淺層/中層', title: '宙船（そらふね） - TOKIO（フル）', rarity: ' 稀有', prefix: ' ', suffix: " high_note Music Lounge" },
    { date: '2017-08-16', path: '⛩︎', pathUrl: 'https://youtu.be/SEtbAEjanWo?si=dFbA43rhkkTGOIjW', area: ' 音樂收藏', category: ' 凝界層', title: '君をのせて 天空の城ラピュタ 井上あずみ', rarity: ' 稀有', prefix: ' ', suffix: " high_note Music Lounge" },
    { date: '2020-07-22', path: '⛩︎', pathUrl: 'https://youtu.be/bMuIoZVbDMM?si=_HgzZmUgnMmbA70m', area: ' 音樂收藏', category: ' 淺層/中層', title: '恋愛サーキュレーション - 花澤香菜（フル）', rarity: ' 傳奇', prefix: ' ', suffix: " high_note Music Lounge" },
    { date: '2015-08-12', path: '⛩︎', pathUrl: 'https://youtu.be/caF6nJxTejc?si=rmP8oy3PmCdzB6GV', area: ' 音樂收藏', category: ' 淺層', title: '君の知らない物語-supercell', rarity: ' 稀有', prefix: ' ', suffix: " high_note Music Lounge" },
    { date: '2020-01-31', path: '⛩︎', pathUrl: 'https://youtu.be/Bw9n53mQPeE?si=6WHb2CAfYThA7lCO', area: ' 音樂收藏/☯東方Project', category: ' 中層/東方Project音樂', title: '【東方Vocal】Wholovesyourworld「DiGiTALWiNG」【Subbed】', rarity: ' 稀有', prefix: ' ', suffix: " Renkoレンコ" },
    { date: '2021-08-04', path: '⛩︎', pathUrl: 'https://youtu.be/-RRFvUvofjw?si=-SKQ0uqJt_GHQCDe', area: ' 音樂收藏', category: ' 臨界層/中層', title: 'Watashihe', rarity: ' 稀有', prefix: ' ', suffix: " ryo (supercell)" },
    { date: '2017-09-12', path: '⛩︎', pathUrl: 'https://youtu.be/BLbt5k9I2JE?si=AGVtszA0ZXyuxc38', area: ' 音樂收藏/☯東方Project', category: ' 中層/東方Project音樂', title: '【自作】東方Project - The Scarlet Garden / Remilia × Flandre', rarity: ' 魔法', prefix: ' 純音樂', suffix: " Piano Room No.1 一號琴房 (Candy Tsai)" },
    { date: '2014-04-20', path: '⛩︎', pathUrl: 'https://youtu.be/b-4X5wO8JF0?si=xDPPHBhT2kqa9ZBe', area: ' 音樂收藏', category: ' 中層', title: 'Bokurano(Our) let it be (ぼくらのレットイットビー) // Full piano ver. [Rui]', rarity: ' 魔法', prefix: ' 純音樂', suffix: " Rui Ruii the Seal Pianist" },
    { date: '2020-05-18', path: '⛩︎', pathUrl: 'https://youtu.be/s50vvwTystA?si=OJyitMAYt49Bgx7E', area: ' 休閒牧場', category: ' 休閒牧場', title: 'Cute Lamb Needs Attention', rarity: ' 魔法', prefix: ' 療癒', suffix: " Lee Walters" },
    { date: '2018-05-20', path: '⛩︎', pathUrl: 'https://youtu.be/UGa8eReR_ns?si=yMuLLbElBkpPG5_S', area: ' 休閒牧場', category: ' ACG同好會', title: 'CliffSide | 卡通系列先導片', rarity: ' 魔法', prefix: ' 動畫', suffix: " Liam Vickers Animation" },
    { date: '2018-05-03', path: '⛩︎', pathUrl: 'https://youtu.be/Nbu_j_a8Kpo?si=ZMorD0EqSPNe-kuu', area: ' 休閒牧場', category: ' ACG同好會', title: '【 戰神 】(2018)7小時電影剪輯版 - 中文完整版 - PS4 Pro劇情電影2K60FPS -战神4-GOD OF WAR 4 All Cutscenes Movie(Game Movie)', rarity: ' 魔法', prefix: ' 劇情', suffix: " Semenix Gaming" },
    { date: '2018-04-20', path: '⛩︎', pathUrl: 'https://youtu.be/XclPhP6dbbw?si=QpvpHel8JtDFGxmd', area: ' 休閒牧場', category: ' ACG同好會', title: 'PS4 戰神3 God of War III 中文劇情剪輯', rarity: ' 魔法', prefix: ' 劇情', suffix: " GoodLuck" },
    { date: '2018-03-19', path: '⛩︎', pathUrl: 'https://youtu.be/F8vIXzSH-js?si=E0cYeVxpfdyALLug', area: ' 休閒牧場/☯東方Project', category: ' ACG同好會/二次創作', title: '【東方偶像鄉 MMD】踢館', rarity: ' 稀有', prefix: ' ', suffix: " 9bluewind9" },
    { date: '2018-01-28', path: '⛩︎', pathUrl: 'https://youtu.be/QrEfHZRRsbM?si=-wlYOXJTjj17D_Zn', area: ' 休閒牧場', category: ' 體育運動', title: '20180128【812】MIT台灣誌 聖稜線！ 探險台灣十五年 加利山頂 臥看聖稜霞光', rarity: ' 一般', prefix: ' ', suffix: " 鳳雩晞風" },
    { date: '2018-01-25', path: '⛩︎', pathUrl: 'https://youtu.be/5cA6c7DTLpI?si=JkTfZffPEi2c7r50', area: ' 休閒牧場', category: ' 這是什麼酷酷的東西', title: '寂寞男子買吸塵器解決需求，被店員警告老二會被吸斷 (中文字幕)', rarity: ' 魔法', prefix: ' ', suffix: " B.C.&Lowy" },
    { date: '2017-09-18', path: '⛩︎', pathUrl: 'https://youtu.be/6k-ywVYdAsg?si=T6Ryz9M07ndAVjdM', area: ' 休閒牧場', category: ' 這是什麼酷酷的東西', title: '網球女將贏得美網冠軍後受訪，不打官腔的真心話回答讓人笑翻 (中文字幕)', rarity: ' 魔法', prefix: ' ', suffix: " B.C.&Lowy" },
    { date: '2017-09-06', path: '⛩︎', pathUrl: 'https://youtu.be/65nfbW-27ps?si=ufsuEVCehPk3kmK8', area: ' 休閒牧場', category: ' 這是什麼酷酷的東西', title: '每天一張自拍 - 12歲到結婚', rarity: ' 一般', prefix: ' ', suffix: " Hugo Cornellier" },
    { date: '2017-04-25', path: '⛩︎', pathUrl: 'https://youtu.be/Q-pwoX_n8WQ?si=rrk2s5fQ8E3bEshH', area: ' 休閒牧場', category: ' 這是什麼酷酷的東西', title: '黑人之間的種族歧視！單口喜劇 有英國腔的黑人 中文字幕', rarity: ' 魔法', prefix: ' ', suffix: " Albert Susko" },
    { date: '2015-07-21', path: '⛩︎', pathUrl: 'https://youtu.be/5xKNNMz-xCM?si=hTyIjFvds-9HFqdx', area: ' 休閒牧場', category: ' ACG同好會', title: '[Preview] Bassjackers - Savior (Reez & KSHMR Remix)', rarity: ' 魔法', prefix: ' 動畫', suffix: " Dávid Dulai" },
    { date: '2015-01-29', path: '⛩︎', pathUrl: 'https://youtu.be/kn271kr_ks0?si=tQsg7bcq1Q8BuNKv', area: ' 休閒牧場', category: ' 這是什麼酷酷的東西', title: 'AUS OPEN 2015 - Djokovic v Abrams Semi-Final', rarity: ' 魔法', prefix: ' ', suffix: " timtimfed" },
    { date: '2015-05-01', path: '⛩︎', pathUrl: 'https://youtu.be/G5A6tXZbeCs?si=POqbTwzYz0E-RU_T', area: ' 休閒牧場/RWBY', category: ' ACG同好會/二次創作', title: 'RWBY AMV - Happy May Day!! xx', rarity: ' 魔法', prefix: ' RWBY', suffix: " queenbee" },
    { date: '2015-01-21', path: '⛩︎', pathUrl: 'https://youtu.be/r-Sq2xpUuXM?si=hMI0U5fc7PU_J8pc', area: ' 休閒牧場/RWBY', category: ' ACG同好會/二次創作', title: 'She Wants to Dance // RWBY AMV // Thank you for 1000+ subs!!!', rarity: ' 魔法', prefix: ' RWBY', suffix: " shiftychaos" },
    { date: '2014-09-17', path: '⛩︎', pathUrl: 'https://youtu.be/-vj3ULyrpt8?si=ndhkFkw-ItgLOdqM', area: ' 休閒牧場/RWBY', category: ' ACG同好會/二次創作', title: 'RWBY AMV - End Of My Days', rarity: ' 魔法', prefix: ' RWBY', suffix: " queenbee" },
    { date: '2014-09-13', path: '⛩︎', pathUrl: 'https://youtu.be/t8a4bP3MayQ?si=r-N6th8fVNXJ_VaX', area: ' 休閒牧場/RWBY', category: ' ACG同好會/二次創作', title: 'RWBY AMV - Centuries', rarity: ' 稀有', prefix: ' RWBY', suffix: " queenbee" },
    { date: '2014-09-05', path: '⛩︎', pathUrl: 'https://youtu.be/69g-2pARI7E?si=vgThrGf7i2gYhkOh', area: ' 休閒牧場/RWBY', category: ' ACG同好會/二次創作', title: 'RWBY AMV - Perfect // Collab', rarity: ' 魔法', prefix: ' RWBY', suffix: " queenbee" },
    { date: '2014-08-10', path: '⛩︎', pathUrl: 'https://youtu.be/j3IwB3C5gAA?si=eJ4SIErafVI2YjWp', area: ' 休閒牧場/☯東方Project', category: ' ACG同好會/二次創作', title: '東方 Project | Touhou Minecraft 東方 マインクラフト | Touhou Gensokyo Project ☯ 3.8/4【4K UHD】❚Outdated❚', rarity: ' 稀有', prefix: ' 遊戲/Minecraft', suffix: " 2hu 2hu" },
    { date: '2014-04-30', path: '⛩︎', pathUrl: 'https://youtu.be/rCKyJEGLBgE?si=qYDpDtMppUOKao70', area: ' 休閒牧場', category: ' ACG同好會', title: 'The Distant Touch', rarity: ' 魔法', prefix: ' 動畫', suffix: " Jun Chen" },
    { date: '2013-06-24', path: '⛩︎', pathUrl: 'https://youtu.be/I0BR3n7q7A4?si=I1r5sjOltHXZBCfS', area: ' 休閒牧場/☯東方Project', category: ' 二次創作/ACG同好會', title: '【東方Project】墨韻東方-幻想鄉宣傳旅遊片⌘ᴴᴰ', rarity: ' 傳奇', prefix: ' ', suffix: " Flandre Scarlet" },
    { date: '2011-09-03', path: '⛩︎', pathUrl: 'https://youtu.be/GSv3nzemR3w?si=Hg0L1_uTsq3Y_EWD', area: ' 休閒牧場/☯東方Project', category: ' 二次創作/ACG同好會', title: '東方非想天則ムービー「Bad Apple!!×東方非想天則」', rarity: ' 傳奇', prefix: ' ', suffix: " th0503" },
    { date: '2019-01-19', path: '⛩︎', pathUrl: 'https://youtu.be/F7qDDJ2iaVE?si=XMgbTS5L1vrIQvQm', area: ' 休閒牧場', category: ' 這是什麼酷酷的東西', title: '有隆乳.被LED照射後.會不會發光!?!?!?!?日本人真是無極限~ XDD', rarity: ' 一般', prefix: ' ', suffix: " MK Memory" },
    { date: '2008-09-14', path: '⛩︎', pathUrl: 'https://youtu.be/gJeehEbfork?si=0_5IYHWQcN2qS5pq', area: ' 休閒牧場', category: ' 這是什麼酷酷的東西', title: '打架會裝死的松鼠', rarity: ' 魔法', prefix: ' ', suffix: " j52348" },
    { date: '2016-05-10', path: '⛩︎', pathUrl: 'https://youtu.be/az2Q7pjClYM?si=fOJURTgZoOeqi-sK', area: ' ☯東方Project/音樂收藏', category: ' 淺層/中層/東方Project音樂', title: '【東方Vocal／Traditional Rock】 祭符「神遊びの唄」 「凋叶棕」【ENG Subs】', rarity: ' 魔法', prefix: ' ', suffix: " Kappashiro" },
    { date: '2020-09-08', path: '⛩︎', pathUrl: 'https://youtu.be/_XPgQNxnGmU?si=C1dgSEnPp2gb2IO5', area: ' ☯東方Project/音樂收藏', category: ' 中層/東方Project音樂', title: '【東方Vocal／Pop】 Glass Eyes 「紺碧studio」', rarity: ' 魔法', prefix: ' ', suffix: " Tenshi Hinanawi" },
    { date: '2014-04-22', path: '⛩︎', pathUrl: 'https://youtu.be/_Udvf598Iic?si=Y6Bfjb4WOliT4Eji', area: ' ☯東方Project/音樂收藏', category: ' 中層/東方Project音樂', title: '[東方 Folk/Instrumental] [CrossGear] 童祭 ～あの日の夏祭り～', rarity: ' 魔法', prefix: ' 純音樂', suffix: " The Little Pagoda" },
    { date: '2017-08-14', path: '⛩︎', pathUrl: 'https://youtu.be/_pjRJ5rV-2o?si=nkCpiFECSBi9-5HH', area: ' 音樂收藏', category: ' 中層/臨界層', title: '終物語【OP】おうぎダーク', rarity: ' 稀有', prefix: ' ', suffix: " toride16" },
    { date: '2019-01-03', path: '⛩︎', pathUrl: 'https://youtu.be/_OW9Bt7hJfQ?si=xlKWBtwABWPtr4jk', area: ' 音樂收藏', category: ' 中層/臨界層', title: 'Kimino Shiranai Monogatari', rarity: ' 傳奇', prefix: ' ', suffix: " ryo (supercell)" },
    { date: '2019-11-07', path: '⛩︎', pathUrl: 'https://youtu.be/0I4pQ2ve_fw?si=e-YCPTj6mAuqnkRS', area: ' 音樂收藏', category: ' 中層/臨界層', title: 'my long forgotten cloistered sleep (unreleased work of Xenosaga)', rarity: ' 稀有', prefix: ' ', suffix: " 梶浦由記 / Yuki Kajiura Official" },
    { date: '2021-02-28', path: '⛩︎', pathUrl: 'https://youtu.be/_5RW17PWB8E?si=NMYTrj_kNU3ovB3B', area: ' 音樂收藏', category: ' 中層', title: 'VERSUS / VESPERBELL [Official Music Video]', rarity: ' 魔法', prefix: ' ', suffix: " VESPERBELL" },
    { date: '2018-12-22', path: '⛩︎', pathUrl: 'https://youtu.be/9wE3E5BQOzc?si=sHvZbQegAxejcxEm', area: ' 音樂收藏', category: ' 中層', title: '陳嫺靜 - 輕輕 (Official Visual)', rarity: ' 魔法', prefix: ' ', suffix: " 陳嫺靜" },
    { date: '2014-08-17', path: '⛩︎', pathUrl: 'https://youtu.be/9I721cbBucY?si=bmW2zWdwKWTD8jQE', area: ' 音樂收藏', category: ' 臨界層', title: 'Kheops - From Taipei To Oulan Bator', rarity: ' 稀有', prefix: ' ', suffix: " UnknownMStyle" },
    { date: '2016-10-05', path: '⛩︎', pathUrl: 'https://youtu.be/9hE1XIBJj48?si=WLzFDFU4R4S-kM0g', area: ' ☯東方Project/音樂收藏', category: ' 中層/東方Project音樂', title: 'ᴴᴰ【東方Vocal】Yonder Voice｜花時計と夢【中日English附詞】', rarity: ' 魔法', prefix: ' ', suffix: " 萌樂 ‧ Meng Yue ᴴᴰ" },
    { date: '2012-04-28', path: '⛩︎', pathUrl: 'https://youtu.be/8sGgffiuFXY?si=rQlm5XEL2MAdVSRV', area: ' ☯東方Project/音樂收藏', category: ' 中層/東方Project音樂', title: '童祭 〜 for Wedding On Vocal', rarity: ' 傳奇', prefix: ' ', suffix: " 博麗神社例大祭" },
    { date: '2008-08-01', path: '⛩︎', pathUrl: 'https://youtu.be/8brDCRuXMzo?si=Rop0puXIfXe8XjUi', area: ' ☯東方Project/音樂收藏', category: ' 中層/東方Project音樂', title: '東方vocalBGM-Regression to origin-', rarity: ' 魔法', prefix: ' ', suffix: " 璃紅" },
    { date: '2018-12-08', path: '⛩︎', pathUrl: 'https://youtu.be/82hJffyJ5hY?si=HpK2ZdTPX99VuUui', area: ' 音樂收藏', category: ' 深層', title: 'Cjbeards - Fire and Thunder', rarity: ' 稀有', prefix: ' 純音樂', suffix: " Cjbeards" },
    { date: '2016-04-07', path: '⛩︎', pathUrl: 'https://www.nicovideo.jp/watch/sm28580854', area: ' 音樂收藏', category: ' 中層', title: '「いかないで」吉他✽英語試唱【Mes】', rarity: ' 魔法', prefix: ' ', suffix: " Mes" },
    { date: '2020-07-12', path: '⛩︎', pathUrl: 'https://youtu.be/7xboF1DwHqQ?si=0gapKnTJQlibIxRT', area: ' ☯東方Project/音樂收藏', category: ' 東方Project音樂/凝界層', title: 'TOUHOU PIANO MEDLEY from TAMusic グランドピアノ生演奏で、1時間東方癒やし演奏してみた', rarity: ' 魔法', prefix: ' 純音樂', suffix: " TAM [タム] ViolinPiano 放浪のバイオリニスト" },
    { date: '2019-01-03', path: '⛩︎', pathUrl: 'https://youtu.be/7OGQ0KRitvI?si=nI2LLSaazzmsQXGI', area: ' 音樂收藏', category: ' 中層', title: 'Mousou Express', rarity: ' 魔法', prefix: ' ', suffix: " MONOGATARI Series - 主題" },
    { date: '2009-07-02', path: '⛩︎', pathUrl: 'https://youtu.be/7MaF-bWeLGw?si=O3q96Gt0sR9CYv1B', area: ' 音樂收藏', category: ' 淺層', title: 'RADWIMPS - おしゃかしゃま [Official Music Video]', rarity: ' 一般', prefix: ' ', suffix: " RADWIMPS" },
    { date: '2013-08-27', path: '⛩︎', pathUrl: 'https://youtu.be/7ltt-4fPSk4?si=rYd8uOxbJLrXEOJp', area: ' ☯東方Project/音樂收藏', category: ' 凝界層/東方Project音樂', title: '[東方 Vocal] [Liz Triangle] ありがとう', rarity: ' 魔法', prefix: ' ', suffix: " The Little Pagoda" },
    { date: '2020-01-09', path: '⛩︎', pathUrl: 'https://youtu.be/7LthTzz26Hc?si=hLDP-BaFTvGs6F4M', area: ' ☯東方Project/音樂收藏', category: ' 淺層/東方Project音樂', title: '【東方Vocal PV】 花月夜 「Yonder Voice」【Subbed】', rarity: ' 魔法', prefix: ' ', suffix: " Tenshi Hinanawi" },
    { date: '2021-03-09', path: '⛩︎', pathUrl: 'https://youtu.be/5azL34UHfiA?si=e97m97BbeJE_6HU1', area: ' 音樂收藏', category: ' 淺層', title: 'aikoi', rarity: ' 稀有', prefix: ' ', suffix: " FictionJunction Official YouTube Channel" },
    { date: '2021-01-20', path: '⛩︎', pathUrl: 'https://youtu.be/4O0OIfBCKIA?si=YtkzcGlycPUaquMp', area: ' ☯東方Project/音樂收藏', category: ' 中層/東方Project音樂', title: '【東方ボーカル】「凋叶棕」いつか沈み行く暗闇の中に', rarity: ' 稀有', prefix: ' ', suffix: " Mystia Lorelei" },
    { date: '2014-08-05', path: '⛩︎', pathUrl: 'https://youtu.be/sG--g1gMrGo?si=R29ZUyGbF7ACH4Jx', area: ' 音樂收藏', category: ' 中層', title: 'Ashes Remain - On My Own (Pseudo Video)', rarity: ' 魔法', prefix: ' ', suffix: " AshesRemainvideos" },
    { date: '2009-03-22', path: '⛩︎', pathUrl: 'https://youtu.be/4-PkAQcuZOw?si=hIQDMCNgBb-a9i3W', area: ' 音樂收藏', category: ' 中層', title: 'Lain opening [Full]', rarity: ' 稀有', prefix: ' ', suffix: " XxLimeberryxX" },
    { date: '2021-07-07', path: '⛩︎', pathUrl: 'https://youtu.be/3fmDG5V73w8?si=Y1bEOGhWr-iN0v5k', area: ' 音樂收藏', category: ' 凝界層', title: '蟲師 - 梅雨の囁き- [作業用,睡眠用BGM,蟲師BGM, Mushishi BGM Covers]', rarity: ' 稀有', prefix: ' 純音樂', suffix: " Koduck Weng's Radio" },
    { date: '2016-06-03', path: '⛩︎', pathUrl: 'https://youtu.be/2i2khp_npdE?si=M8ShFy165j09uB4N', area: ' 音樂收藏', category: ' 中層/臨界層', title: 'Alan Walker - Sing Me To Sleep', rarity: ' 傳奇', prefix: ' ', suffix: ' Alan Walker' },
    { date: '2019-01-03', path: '⛩︎', pathUrl: 'https://youtu.be/14FOPsSCIPs?si=xXMwZpfq3CeAh7by', area: ' 音樂收藏', category: ' 中層', title: 'Platinum Disco', rarity: ' 稀有', prefix: ' ', suffix: ' MONOGATARI Series - 主題' },
    { date: '2019-01-03', path: '⛩︎', pathUrl: 'https://youtu.be/-qm3k3AnoLs?si=zW_ekD_bUDVPJ-XI', area: ' 音樂收藏', category: ' 淺層', title: 'Basket Ball', rarity: ' 稀有', prefix: ' 純音樂', suffix: ' MONOGATARI Series - 主題' },
    { date: '2020-02-23', path: '⛩︎', pathUrl: 'https://youtu.be/-jj-rHDjCvM?si=mSGNK92mXAHaTOZD', area: ' 音樂收藏', category: ' 中層', title: '[ASMR/環境音]夏、海の見える、誰もいない部屋で。/作業用BGM 睡眠用BGM/オリジナル音源', rarity: ' 一般', prefix: ' 白噪音', suffix: ' Sound Forest' },
    { date: '2019-01-27', path: '⛩︎', pathUrl: 'https://youtu.be/-hV1Rv8hsY4?si=ALP6tq_OSKGN4KJs', area: ' 音樂收藏', category: ' 凝界層', title: '【ピアノ】軟鋼琴 - 鏡湖 / Soft Piano Music - Mirror Lake: Relaxing, Calming, Peaceful Piano Music', rarity: ' 一般', prefix: ' 純音樂', suffix: ' Piano Room No.1 一號琴房 (Candy Tsai)' },
    { date: '2018-04-24', path: '⛩︎', pathUrl: 'https://youtu.be/-AJOg5sHoKs?si=xfxngjAX3qsSNdCI', area: ' 音樂收藏', category: ' 中層', title: '《淡い花》ツキウタ。piano arrange.', rarity: ' 一般', prefix: ' ', suffix: ' Plus - Original Music' },
    { date: '2017-04-16', path: '⛩︎', pathUrl: 'https://youtu.be/8Th21hKlQ5Y?si=VA5BtZowNhBVoFnB', area: ' ☯東方Project/音樂收藏', category: ' 臨界層/東方Project音樂', title: 'ᴴᴰ⁶⁰【東方Vocal】Yonder Voice｜夏越【中日English附詞】', rarity: ' 魔法', prefix: ' ', suffix: ' 萌樂 ‧ Meng Yue ᴴᴰ' },
    { date: '2016-01-20', path: '⛩︎', pathUrl: 'https://youtu.be/KBNqWZeX7U4?si=gQK7VAa-BuRi9q2Q', area: ' ☯東方Project/音樂收藏', category: ' 臨界層/東方Project音樂', title: ' Billie Eilish - Bellyache ( cover by J.Fla )', rarity: ' 稀有', prefix: ' 純音樂', suffix: ' LENK64' },
    { date: '2019-01-18', path: '⛩︎', pathUrl: 'https://youtu.be/s_j3E4NpEWQ?si=6lgh-RS0QO3LBG53', area: ' 音樂收藏', category: ' 臨界層', title: ' Billie Eilish - Bellyache ( cover by J.Fla )', rarity: ' 稀有', prefix: ' ', suffix: ' JFlaMusic' },
    { date: '2026-07-15', path: '⛩︎', pathUrl: 'https://gemini.google.com/share/9712e94b6021', area: ' 《青丘茶館》', category: ' 《2026》', title: ' 呆呆教授', rarity: ' 稀有', prefix: ' 編年史', suffix: ' 呆呆叫/' },
    { date: '日期', path: '章節/輿圖', pathUrl: 'https://swallow-234.github.io/swallow_234/%E5%85%AC%E4%BD%88%E6%AC%84', area: '系列勢力', category: '主題 ', title: '標題 ', rarity: '稀有度 ', prefix: '前綴 ', suffix: '後綴 ' }
];
const workData2 = [...workData].sort((a, b) => {
        return b.date.localeCompare(a.date);
    });