// 1. 【核心對照表】定義哪個勢力擁有哪幾個主題
const categoryMap = {
    "《鼠鼠戰團》": ["《審判日誌》", "《公眾人物》", "《主管機關》", "《專案整理》",],
    "《國際》": ["戰爭", "天災", "疫情",],
    "《國內外》": [ "盟邦", "合約", "進出口", "衝突", "賽事", "移工",],
    "《國內》": [ "組織團體","中央政府", "地方政府", "臺北市", "新北市", "桃園市", "臺中市", "臺南市", "高雄市", "基隆市", "新竹市", "嘉義市", "新竹縣", "苗栗縣", "彰化縣", "南投縣", "雲林縣", "嘉義縣", "屏東縣", "宜蘭縣", "花蓮縣", "臺東縣","澎湖縣","金門縣","連江縣",],
    // 💡 如果有新增的勢力，依樣畫葫蘆加在下面即可
};

// 2. 【大全清單】當使用者選回「系列勢力（全部）」時，要秀出的所有主題
const allCategories = [
 "《修道院》修室", "《修道院》修真", "《修道院》修道", "《修道院》修體", "《劇本-講解》", "《商學院》", "《建築學》", "《戰爭學院》", "《法學院》", "《社會學院》", "《禁忌》", "《科博館》", "《數學館》", "《繪圖-講解》", "《語言研究院》", "《醫學院》", "《青丘事務所》", "《青丘書館》", "《音樂-講解》", "吟遊詩章-圓桌會議", "《虛擬人生》", "《遺跡先遣隊》", "《青丘之燕》", "簡介", "《2017》", "《2025》", "《2026》", "《過往紀錄》",
];

// 1. 原始資料庫 (表格1 的真實內容)
//外交與國防：國際、邦交、國防軍事戰略、國家安全。
//經濟與財政：產業發展、貿易、科技創新、國家預算、稅收制度、貨幣供給及金融管理。
//社會與民生：勞動權益、社會福利、住宅正義、公共衛生及醫療保健。
//教育與文化：國民教育、高等教育、體育發展、文化資產保護及文化傳播。
//環境與基礎建設：環境保護、自然生態、氣候變遷因應、交通運輸及公共工程。
//法治與行政：司法改革、治安維護、廉政建設、公務員體制及選舉制度。
//經過專案整理，則為「動動鼠」。
//可以複選。
const workData = [
    { date: '2026-09-02', path: '', pathUrl: '', area: ' 《鼠鼠戰團》', category: ' ', title: '先反對，後面才認同跟上，並宣揚為自己的政績，再將這個說成是自己推行的，其人才跟進的。', rarity: ' ', prefix: ' 鼠鼠模組', suffix: ' ' },
    { date: '2026-08-15', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/高雄市', title: '7.65億蓋高雄三民運動中心…跑步機僅4台、廁所飄臭味<br>※運動中心動土時公布經費約4.01億元，完工卻一路膨脹到7.65億元', rarity: ' ', prefix: ' 預算/補助', suffix: ' 環境與基礎建設<br>經濟與財政<br>社會與民生' },
    { date: '2026-08-17', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/新北市', title: '孝心用錯！替母倒4025公斤椰子殼 新北清潔隊班長貪汙圖利遭訴<br>※亂倒爐渣的才罰6000，廢棄物燃燒都抓不到人，這種底層清潔隊抓的很勤。', rarity: ' ', prefix: ' 掩蓋事件/轉移焦點', suffix: ' 環境與基礎建設<br>法治與行政' },
    { date: '2026-08-19', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府/屏東縣', title: '九鵬測試火箭墜山區目擊居民驚慌屏東縣府籲檢視作業程序', rarity: ' ', prefix: ' ', suffix: ' 外交與國防' },
    { date: '2026-08-17', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: '雞肉漲價撐不住了！菜販曝1物「全台瘋搶大缺貨」：電宰廠連漲3波，關鍵在於「進口雞腿」大缺貨。<br>※超思進口雞蛋。', rarity: ' ', prefix: ' ', suffix: ' 經濟與財政<br>社會與民生' },
    { date: '2026-08-16', path: '', pathUrl: '', area: ' 《國內外》', category: ' 移工', title: '勞動部統計，台灣境內外籍移工人數突破八十八萬人，但失聯移工近十萬人。<br>※將銀行帳戶、手機ＳＩＭ卡賣給詐騙集團犯案。；免費機票', rarity: ' ', prefix: ' 政策弊端', suffix: ' 法治與行政<br>社會與民生<br>經濟與財政' },
    { date: '2026-08-20', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: '孩子一直問訂單咧…總統府中秋採購被迫喊卡 庇護工場心碎求援國人認購<br>※拿納稅人的錢做公益，功勞給自己，這是什麼邏輯？', rarity: ' ', prefix: ' 垃圾行為<br>預算/補助', suffix: ' 社會與民生<br>經濟與財政' },
    { date: '2026-08-21', path: '', pathUrl: '', area: ' 《國內外》', category: ' 賽事', title: '第45屆威廉瓊斯盃男子組賽事「地主保送四強」淪國際笑柄<br>※中華民國籃球協會，訂立「地主中華藍隊保障晉級四強」。', rarity: ' ', prefix: ' 垃圾行為<br>某協會', suffix: ' 教育與文化' },
    { date: '2026-08-22', path: '', pathUrl: '', area: ' 《國內》', category: ' 組織團體', title: '《尼古喵喵》下架惹怒動漫迷！打爆董氏電話疑菸商網軍帶風向<br>※二分化；本土電影黑幫角頭卻不用下架。', rarity: ' ', prefix: ' 某協會<br>自訂義/護航/雙標', suffix: ' 法治與行政' },
    { date: '2026-08-22', path: '', pathUrl: '', area: ' 《國內》', category: ' 組織團體', title: '《尼古喵喵》下架惹怒動漫迷！打爆董氏電話疑菸商網軍帶風向<br>※二分化；國片電影黑幫角頭卻不用下架。', rarity: ' ', prefix: ' 某協會<br>自訂義/護航/雙標', suffix: ' 法治與行政' },
    { date: '2026-08-22', path: '', pathUrl: '', area: ' 《國內外》', category: ' ', title: '台中男閃兵1年不回台？真相超傻眼…竟是被擄去緬甸詐騙園區<br>※弟弟去泰國工作後聯繫不上；判無罪', rarity: ' ', prefix: ' ', suffix: ' 法治與行政' },
    { date: '2026-08-22', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/臺南市/高雄市', title: '抓到了！台南住宅空地藏危險物釀爆炸 來自高雄鼓山業者<br>※大祕寶', rarity: ' ', prefix: ' 垃圾行為', suffix: ' 社會與民生' },
    { date: '2026-08-23', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/臺北市', title: '蔣萬安砍樹讓夜鷺無家可歸<br>※高雄砍樹種光電板', rarity: ' ', prefix: ' 自訂義/護航/雙標', suffix: ' 環境與基礎建設' },
    { date: '2026-06-19', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/臺北市/臺南市', title: '暴雨炸雙北！台南挺過大雨考驗 黃偉哲：願分享治水經驗<br>※2026-08-23台南淹水', rarity: ' ', prefix: ' 自訂義/護航/雙標<br>預算/補助', suffix: ' 環境與基礎建設' },
    { date: '2026-08-24', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/高雄市', title: '高雄前鎮魚市場淹水<br>※地方編三千萬預算整修，中央直接給81億的魚市場', rarity: ' ', prefix: ' 預算/補助', suffix: ' 環境與基礎建設<br>' },
    { date: '2026-08-24', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/臺南市', title: ' 台南大爆炸「里長涉勾串業者」3人遭羈押', rarity: ' ', prefix: ' 垃圾行為<br>黑箱/內定<br>棄保/潛逃<br>無證照/未登記', suffix: ' 環境與基礎建設<br>社會與民生' },
    { date: '2026-08-19', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: ' 70次無照累犯毒駕男黃國維撞死警！', rarity: ' ', prefix: ' 垃圾行為', suffix: ' 法治與行政<br>社會與民生' },
    { date: '2026-08-25', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府/地方政府', title: ' 南部治水預算比台北多？經濟部曝「31年真實數字」驚呆：北北基拿了6成', rarity: ' ', prefix: ' 預算/補助<br>自訂義/護航/雙標', suffix: ' 環境與基礎建設<br>淹水' },
    { date: '2006', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: ' 陳水扁提出華航改名<br>※【華航正名】', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 環境與基礎建設<br>民進黨' },
    { date: '2016', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: ' 民進黨全代會再次提起，蔡英文裁示交付中執會<br>※【華航正名】', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 環境與基礎建設<br>民進黨' },
    { date: '2020', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: ' 交通部長林佳龍挺華航正名<br>※【華航正名】', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 環境與基礎建設<br>民進黨' },
    { date: '2016', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: ' 蔡英文競選總統時提，住宅三箭，其中一箭就是「杜絕房市炒作」<br>※實價登錄', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '2019', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: ' 行政院提出「平均地權條例」也就是「實價登錄2.0」的修法<br>※實價登錄', rarity: ' ', prefix: ' 承諾/政見<br>魚目混珠', suffix: ' 法治與行政<br>民進黨' },
// 資料整理進度
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 工會法', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 宗教團體法', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 中央與地方財政收支規劃法', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 公益信託法修正', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 實坪制', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' 《國內外》', category: ' 進出口', title: ' 柯建銘兒子柯鈞耀 不知情 不運毒 不靠爸 / 憑一己之力 改變台灣司法', rarity: ' ', prefix: ' 卸責/轉嫁', suffix: ' 法治與行政' },
    { date: '2026-08-23', path: '', pathUrl: '', area: ' 《國內》', category: ' ', title: ' 高中課文溺水竟抓到救生員「雞雞」－翰林版第五冊收錄的文章〈泳褲〉', rarity: ' ', prefix: ' 預算/補助', suffix: ' 教育與文化' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 鍾文智', rarity: ' ', prefix: ' 棄保/潛逃', suffix: ' 法治與行政' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 郭哲敏', rarity: ' ', prefix: ' 棄保/潛逃', suffix: ' 法治與行政' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 國會聽證調查制度', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 國會席次聯立制', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 妨礙司法公正罪', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 不法關說罪', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 不法餽贈罪', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 影響力交易罪', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 吹哨者保護法', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 棄保潛逃罪', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 集會遊行惡法', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 最低工資法', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 兩岸協議監督條例', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 反媒體壟斷法', rarity: ' ', prefix: ' 承諾/政見', suffix: ' 法治與行政<br>民進黨' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 朱國榮', rarity: ' ', prefix: ' 棄保/潛逃', suffix: ' 法治與行政' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 陳偉志', rarity: ' ', prefix: ' 棄保/潛逃', suffix: ' 法治與行政' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 林秉文', rarity: ' ', prefix: ' 棄保/潛逃', suffix: ' 法治與行政' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: ' 涂誠文', rarity: ' ', prefix: ' 棄保/潛逃', suffix: ' 法治與行政' },
    { date: '2024-09-08', path: '⛨', pathUrl: 'https://sites.google.com/view/swallow-tpp/%E5%B0%8D%E6%8A%97%E7%B6%A0%E8%89%B2%E9%BB%A8%E5%9C%8B-%E6%B0%91%E7%9C%BE%E5%85%A8%E5%9C%8B%E9%96%8B%E8%AC%9B20240908%E4%B8%8A%E8%A1%97/%E5%85%AC%E6%B0%91%E6%80%92%E5%90%BC%E7%AC%AC%E4%B8%80%E7%AB%99-%E5%9C%B0%E9%BB%9E%E5%8F%B0%E5%8C%97%E5%B8%82%E4%B8%AD%E6%AD%A3%E5%8D%80%E6%BF%9F%E5%8D%97%E8%B7%AF%E4%B8%8A-%E6%99%82%E9%96%9398-%E6%97%A51800-2030?authuser=0', area: ' 《鼠鼠戰團》<br>《國內》', category: ' 組織團體<br>中央政府', title: ' 📍公民怒吼第一站 地點：台北市中正區濟南路上 時間：9/8 （日）18:00 - 20:30', rarity: ' 重度', prefix: ' 就是鼠', suffix: ' 法治與行政<br>媒體' },
    { date: '2024-09-08', path: '⛨', pathUrl: 'https://sites.google.com/view/swallow-tpp/%E5%B0%8D%E6%8A%97%E7%B6%A0%E8%89%B2%E9%BB%A8%E5%9C%8B-%E6%B0%91%E7%9C%BE%E5%85%A8%E5%9C%8B%E9%96%8B%E8%AC%9B20240908%E4%B8%8A%E8%A1%97?authuser=0', area: ' 《鼠鼠戰團》<br>《國內》', category: ' 組織團體<br>中央政府', title: ' 【對抗綠色黨國 民眾全國開講】上街！！', rarity: ' 重度', prefix: ' 就是鼠', suffix: ' 法治與行政<br>媒體' },
    { date: '2024-09-13', path: '⛨', pathUrl: 'https://sites.google.com/view/swallow-tpp/justice%E7%82%BA%E5%8F%B8%E6%B3%95%E6%AD%A3%E7%BE%A9%E7%AB%99%E5%87%BA%E4%BE%86%E5%85%A8%E5%8F%B0%E5%A0%B4%E6%AC%A1/%E6%96%B0%E5%8C%97%E6%96%B0%E8%8E%8A%E9%AB%94%E8%82%B2%E9%A4%A8%E5%A4%96-%E6%96%B0%E5%8C%97%E5%B8%82%E6%96%B0%E8%8E%8A%E5%8D%80%E4%B8%AD%E8%8F%AF%E8%B7%AF%E4%B8%80%E6%AE%B5%E5%85%AC%E5%9C%92%E8%B7%AF%E5%8F%A3?authuser=0', area: ' 《鼠鼠戰團》<br>《國內》', category: ' 組織團體<br>中央政府', title: ' 新北新莊體育館外(新北市新莊區中華路一段/公園路口)', rarity: ' 重度', prefix: ' 就是鼠', suffix: ' 法治與行政<br>媒體' },
    { date: '2024-09-14', path: '⛨', pathUrl: 'https://sites.google.com/view/swallow-tpp/justice%E7%82%BA%E5%8F%B8%E6%B3%95%E6%AD%A3%E7%BE%A9%E7%AB%99%E5%87%BA%E4%BE%86%E5%85%A8%E5%8F%B0%E5%A0%B4%E6%AC%A1/%E5%98%89%E7%BE%A9%E5%B8%82%E5%8D%97%E9%A0%86%E5%AE%AE-%E5%98%89%E7%BE%A9%E5%B8%82%E6%9D%B1%E5%8D%80%E8%88%88%E6%A5%AD%E6%9D%B1%E8%B7%AF399%E8%99%9F?authuser=0', area: ' 《鼠鼠戰團》<br>《國內》', category: ' 組織團體<br>中央政府', title: ' 嘉義市南順宮(嘉義市東區興業東路399號)', rarity: ' 重度', prefix: ' 就是鼠', suffix: ' 法治與行政<br>媒體' },
    { date: '2024-09-20', path: '⛨', pathUrl: 'https://sites.google.com/view/swallow-tpp/justice%E7%82%BA%E5%8F%B8%E6%B3%95%E6%AD%A3%E7%BE%A9%E7%AB%99%E5%87%BA%E4%BE%86%E5%85%A8%E5%8F%B0%E5%A0%B4%E6%AC%A1/%E9%9B%86%E7%B5%90%E7%82%BA%E5%8F%B8%E6%B3%95%E6%AD%A3%E7%BE%A9%E7%AB%99%E5%87%BA%E4%BE%86%E9%AB%98%E9%9B%84%E5%8F%B0%E5%8D%97%E5%8F%B0%E4%B8%AD%E5%A0%B4%E6%AC%A1%E6%88%B6%E5%A4%96%E9%96%8B%E8%AC%9B?authuser=0', area: ' 《鼠鼠戰團》<br>《國內》', category: ' 組織團體<br>中央政府', title: ' 【集結！為司法正義站出來】高雄、台南、台中場次戶外開講', rarity: ' 重度', prefix: ' 就是鼠', suffix: ' 法治與行政<br>媒體' },
    { date: '2024-10-05', path: '⛨', pathUrl: 'https://sites.google.com/view/swallow-tpp/2024%E5%B9%B410%E6%9C%8805%E6%97%A5-%E9%90%B5%E8%8D%89%E9%9B%86%E7%B5%90?authuser=0', area: ' 《鼠鼠戰團》<br>《國內》', category: ' 組織團體<br>中央政府', title: ' 鐵草集結', rarity: ' 重度', prefix: ' 就是鼠', suffix: ' 法治與行政<br>媒體' },
    { date: '2026-03-29', path: '⛨', pathUrl: 'https://sites.google.com/view/swallow-tpp/%E5%80%89%E5%BA%AB/-%E6%88%B0%E5%87%BA%E4%BE%86', area: ' 《鼠鼠戰團》<br>《國內》', category: ' 組織團體<br>中央政府', title: ' 🔥𝟯𝟮𝟵 戰出來！', rarity: ' 重度', prefix: ' 就是鼠', suffix: ' 法治與行政<br>媒體' },
    { date: '2026-07-25', path: '⛨', pathUrl: 'https://sites.google.com/view/swallow-tpp/%E5%80%89%E5%BA%AB/725-%E4%B8%8A%E5%87%B1%E9%81%93-%E8%AD%B7%E9%A3%9F%E5%AE%89', area: ' 《鼠鼠戰團》<br>《國內》', category: ' 組織團體<br>中央政府', title: ' 725 上凱道 護食安', rarity: ' 重度', prefix: ' 就是鼠', suffix: ' 社會與民生<br>食安<br>毒油' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '食農教育法', rarity: ' ', prefix: ' 買兇/威脅', suffix: ' ' },
    { date: '2026-07-11', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/台中市', title: '台中重劃會理事長花15萬買兇！乩童當街毒打地政主任　打到鋁棒斷掉', rarity: ' 中度', prefix: ' 買兇/威脅', suffix: ' 環境與基礎建設<br>法治與行政<br>長春/自辦重劃區' },
    { date: '2026-07-11', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/高雄市', title: '巴威颳強風高雄狀況一堆 11870戶停電、大樓磁磚剝落和號誌桿斷裂', rarity: ' 中度', prefix: ' ', suffix: ' 環境與基礎建設' },
    { date: '2026-07-10', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/臺南市', title: '台南下營一間養雞場昨晚突然停電，價值超過500萬元的4.6萬隻肉雞全部悶死。', rarity: ' 中度', prefix: ' 無證照/未登記', suffix: ' 環境與基礎建設' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '基因改造大豆', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '「特部他林」用於氣喘，孕婦用藥進入到胎兒的腦部裡面，引起神經毒性，造成神經發展與行為問題、精神疾病、認知與運動功能影響、學校表現比較差。', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '軍方採購單價120元長效期戰備飲水', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '蘇姓前行政院院長祖父向日本人告密有人造反，結果500多人被日本人處死？', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '2026-03-27', path: '', pathUrl: '', area: ' 《國內外》', category: ' 移工', title: '印度男高雄街頭「打野食」 「偽娘」遭闖空門強逼口交', rarity: ' 中度', prefix: ' ', suffix: ' 社會與民生' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '三立高鐵照片附註未成年、露三點、道歉、野外露', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '偵查隊長 利用警察職位調查 小草個資', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '2026-04-08', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/臺南市', title: '台南掩埋場又起火！學甲廢棄物山全面燃燒，空拍畫面驚人', rarity: ' 重度', prefix: ' ', suffix: ' 環境與基礎建設<br>空汙' },
    { date: '2026-04-11', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/臺南市', title: '吸毒男幻覺砍人險奪命 法官判無罪理由曝', rarity: ' 重度', prefix: ' ', suffix: ' 法治與行政<br>社會與民生<br>吸毒' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '三立新聞：台灣性犯罪比印度高！', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '公督盟和代表人各遭裁罰10萬 張斯綱：被認證違法憑什麼評鑑別人？', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '詐團首腦撈上億！徐巧芯大姑委任律師游光德「剪斷手環」棄保潛逃', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '健康委員會「1年607億」要幹嘛？', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '民進黨被共諜滲透', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '財劃法跳票', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '假的抗中保台', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '實質廢死一致決', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '黨庫通國庫', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '民進黨長期經營檢調關係', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '黨檢媒一體 迫害政敵', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '大內宣養綠媒 95億', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '賴清德幫殺人犯開記者會翻車', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '疫情期間爭議', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '樂樂養雞場 2019', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '放跑鍾文智', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '長老教會拿原民會補助辦青鳥宴', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '勞動基金虧損', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '揭弊者保護法跳票｜吹哨里長被殺', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '社宅20萬戶跳票', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '司法院每年去法國勘查違憲', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '用納稅錢支付行銷費用', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '會計法國務機要費除罪化', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '宣傳片零日攻擊一億多', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '印度勞工引進說謊', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '駐美代表官邸半年花800萬！', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: 'TaiwanPlus 大外宣公視英文媒體：4年58億| 2億樂齡｜283億數位部預算', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '伍麗華用原民會族群委員養樁腳年薪一百多萬', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '原民會145萬個人寫真集', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '就安基金養側翼2872萬', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '「目的良善」勞發署北部分署長謝宜容霸凌下屬致其自縊 5年7251萬濫用就安基金', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '慶富獵雷艦案88億', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '大同炒股案', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: 'NCC鏡電視施壓裴瑋', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '空軍福興營區收賄2800萬', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '高雄足球場3.5億紐西蘭女足拒絕出賽', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '新竹棒球場12億 挖出新竹大秘寶', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '前瞻8800億爭議', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '體協40億', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '司法關說', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '做票疑雲', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '台南光電黑金88槍21億 邱莉莉議長賄選案', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '鄭文燦弊案', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '酬庸吳乃仁賤賣台糖土地欠1.6億', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '科學城物流', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '台南麻豆公五市場', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '陳明文幫寶和會槍手辦特見', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: 'imb詐騙案陳歐珀', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '88會館洗錢2476億', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '如興弊案15億到中國', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '數位身分證10億', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '數發部 一年283億預算', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '防彈衣纖維板賺上億', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '聯合再生70億', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '台鐵行控4.0: 7500萬', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '理立系統2.2億', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '力暘光電上百億', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '超思雞蛋10億', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '台鹽綠能被掏空8.6億', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' 《國內》', category: ' 組織團體', title: '天道盟國策顧問黃承國', rarity: ' 重度', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' 《國內》', category: ' 組織團體', title: '天道盟 未成年', rarity: ' 重度', prefix: ' ', suffix: ' ' },
    { date: '2025-12-12', path: '', pathUrl: '', area: ' 《國內》', category: ' 組織團體', title: '「詐騙22億」王牌交易所竟藏綠媒　三立「收錢幫洗白」害更多人受害<br>※詐騙/媒體/三立電視/創造智能/ACE王牌交易所/萱篆公司/BIBO願望合夥人/陶晶瑩/陳零九/邱勝翊/謝詩瑩/姜建良/塏薾股份有限公司/高明慧/林慧珍/李燕南/林淑芬/精舍/NCC', rarity: ' 重度', prefix: ' ', suffix: ' 社會與民生' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' 中央政府', title: '高端合約保密', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' ', category: ' ', title: '非州豬瘟', rarity: ' ', prefix: ' ', suffix: ' ' },
    { date: '', path: '', pathUrl: '', area: ' 《國內》', category: ' ', title: '普悠瑪事件', rarity: ' 重度', prefix: ' ', suffix: ' 環境與基礎建設' },
    { date: '2026-03-09', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府/地方政府/花蓮縣', title: '花蓮光復洪災19死偵結！鄉長林清水涉廢弛職務 起訴求刑10年', rarity: ' 重度', prefix: ' 卸責/轉嫁', suffix: ' 環境與基礎建設<br>法治與行政<br>社會與民生' },
    { date: '2025-02-05', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: '雲端發票抽獎爭議 國稅局：調查局查無不法、向廠商求償2400萬', rarity: ' 中度', prefix: ' 黑箱/內定', suffix: ' 法治與行政<br>社會與民生<br>財政部<br>發票' },
    { date: '2026-03-16', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: '內政部長劉世芳拒絕接受立委李貞秀質詢', rarity: ' 重度', prefix: ' ', suffix: ' 法治與行政<br>質詢' },
    { date: '2026-03-16', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: '行政院長卓榮泰今年3月赴東京觀賞世界棒球經典賽（WBC）的收據', rarity: ' 重度', prefix: ' 偽造/竄改<br>預算/補助', suffix: ' 外交與國防/經濟與財政<br>空軍松山基地指揮部/包機' },
    { date: '2026-03-19', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: '文化部補助：玻璃睪丸/懶趴嘸洗(我要幹狗的屁眼)。', rarity: ' 中度', prefix: ' 預算/補助', suffix: ' 經濟與財政<br>教育與文化<br>歌曲/金音獎/文化部' },
    { date: '2026-06-09', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/臺南市', title: '台南檳榔攤竟收美金？酒駕公告驚見「異世界合成圖」', rarity: ' 重度', prefix: ' 偽造/竄改', suffix: ' 法治與行政' },
    { date: '2026-06-19', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: '台電為了填補超過新台幣3,600億元的累積虧損，向中華郵政（郵局）取得3,000億元資金。', rarity: ' 重度', prefix: ' ', suffix: ' 經濟與財政<br>社會與民生' },
    { date: '2026-06-22', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: '蘇巧慧「家族違法鍊金」<br>※威如科技/akaSwap/三立媒體/創造智能/ACE王牌交易所/萓篆股份有限公司', rarity: ' 重度', prefix: ' 預算/補助', suffix: ' 經濟與財政' },
    { date: '2026-06-22', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: '年度無人機總預算', rarity: ' 重度', prefix: ' 預算/補助', suffix: ' 經濟與財政<br>貪汙' },
    { date: '2026-06-18', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: '同一支手機號碼「0983***927」在短時間內重複中獎 6次（包括 Apple AirPods 4 和 iPad 11）。', rarity: ' 中度', prefix: ' 黑箱/內定', suffix: ' 教育與文化<br>社會與民生<br>台灣運彩/運動部' },
    { date: '2026-04-23', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/臺南市', title: '帶頭作亂！台南環保局「垃圾倒水溝」民眾當場目擊「餵垃圾」痛批太誇張', rarity: ' 中度', prefix: ' ', suffix: ' 環境與基礎建設' },
    { date: '2026-07-03', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: '立委爆會議紀錄遭竄改 通過被改為不通過/事後避孕藥', rarity: ' 重度', prefix: ' 偽造/竄改', suffix: ' 法治與行政' },
    { date: '2026-07-04', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府', title: '1300公噸致癌沙拉油僅回收17公噸 食藥署：雞塊、沙拉醬等成品不回收', rarity: ' 重度', prefix: ' ', suffix: ' 社會與民生<br>食安' },
    { date: '2026-07-05', path: '', pathUrl: '', area: ' 《國內外》', category: ' 賽事', title: '屏東「海洋之子」尤佳琦奪亞運門票 竟遭政府名額作廢？連日本選手都納悶', rarity: ' 重度', prefix: ' 某協會', suffix: ' 教育與文化<br>衝浪協會/國訓中心/運動部' },
    { date: '', path: '', pathUrl: '', area: ' 《國內》', category: ' ', title: '殭屍肉', rarity: ' 重度', prefix: ' ', suffix: ' 社會與民生<br>食安' },
    { date: '', path: '', pathUrl: '', area: ' 《國內》', category: ' ', title: '光電板水', rarity: ' 重度', prefix: ' ', suffix: ' 社會與民生<br>食安' },
    { date: '', path: '', pathUrl: '', area: ' 《國內》', category: ' ', title: '爐渣米', rarity: ' 重度', prefix: ' ', suffix: ' 社會與民生<br>食安' },
    { date: '2023-08-20', path: '', pathUrl: '', area: ' 《國內外》', category: ' 進出口', title: '發芽馬鈴薯', rarity: ' 重度', prefix: ' ', suffix: ' 社會與民生<br>食安' },
    { date: '2026-03-24', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/新北市/', title: '食品添加物超標', rarity: ' 重度', prefix: ' ', suffix: ' 社會與民生<br>食安' },
    { date: '2023-09-22', path: '', pathUrl: '', area: ' 《國內外》', category: ' 進出口', title: '進口雞蛋', rarity: ' 重度', prefix: ' ', suffix: ' 社會與民生<br>食安' },
    { date: '2026-04-27', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/臺北市/高雄市/彰化縣', title: '農藥超標茶葉', rarity: ' 重度', prefix: ' ', suffix: ' 社會與民生<br>食安' },
    { date: '2018-04-20', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/臺北市/雲林縣', title: '農藥殘留蔬果', rarity: ' 重度', prefix: ' ', suffix: ' 社會與民生<br>食安' },
    { date: '2014-09-11', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/臺北市', title: '黃麴毒素花生', rarity: ' 重度', prefix: ' ', suffix: ' 社會與民生<br>食安' },
    { date: '2014-09-11', path: '', pathUrl: '', area: ' 《國內外》', category: ' 進出口', title: '工業用油／黑心油', rarity: ' 重度', prefix: ' ', suffix: ' 社會與民生<br>食安' },
    { date: '2026-07-06', path: '', pathUrl: '', area: ' 《國內外》', category: ' 進出口', title: '蘇丹紅辣椒粉', rarity: ' 重度', prefix: ' ', suffix: ' 社會與民生<br>食安' },
    { date: '2026-04-23', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/高雄市', title: '濫挖濫倒廢土！「美濃大峽谷」八處巨坑只收到25萬罰鍰 市府：地主名下無財產', rarity: ' 重度', prefix: ' ', suffix: ' 經濟與財政<br>法治與行政<br>環境與基礎建設<br>' },
    { date: '2026-04-24', path: '⛩︎', pathUrl: 'https://www.mofa.gov.tw/CountryInfo.aspx?CASN=2&n=163&sms=33&s=90', area: ' 《國內外》', category: ' 盟邦', title: '王權式民主 (monarchical democracy君主立憲制)', rarity: ' 輕度', prefix: ' 自訂義/護航/雙標', suffix: ' 外交與國防' },
    { date: '2026-05-09', path: '', pathUrl: '', area: ' 《國內外》', category: ' 進出口', title: '賴總統宣布開放巴拉圭禽肉 農業部：對產業影響有限', rarity: ' 輕度', prefix: ' ', suffix: ' 經濟與財政<br>雞肉' },
    { date: '2026-04-10', path: '', pathUrl: '', area: ' 《國內》', category: ' 組織團體', title: '跑山獸1因素被攻擊！專家抖林姓教官真實身分：拿雞毛當令箭', rarity: ' 輕度', prefix: ' 某協會<br>預算/補助', suffix: ' 社會與民生<br>教育與文化<br>中華民國山難救助協會' },
    { date: '2026-04-10', path: '', pathUrl: '', area: ' 《國內》', category: ' 組織團體', title: '跑山獸1因素被攻擊！專家抖林姓教官真實身分：拿雞毛當令箭', rarity: ' 輕度', prefix: ' 某協會', suffix: ' 社會與民生<br>教育與文化<br>中華民國山難救助協會' },
    { date: '2026-05-17', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/嘉義市', title: '國中男遭圍毆，法院認定不符霸凌持續性要件，慰撫金從300萬降至24萬', rarity: ' 一般', prefix: ' ', suffix: ' 法治與行政<br>教育與文化' },
    { date: '2026-05-20', path: '', pathUrl: '', area: ' 《國內外》', category: ' 移工', title: '傳移工狂領50億家屬死亡給付？勞保局：去年查獲357件疑義退件、已修法強化把關', rarity: ' 中度', prefix: ' ', suffix: ' 社會與民生<br>經濟與財政' },
    { date: '2026-06-03', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/新北市', title: '70次無照累犯毒駕男黃國維撞死執勤警！更一審家屬淚求高院嚴懲重判', rarity: ' 一般', prefix: ' ', suffix: ' 法治與行政<br>毒駕' },
    { date: '2026-06-05', path: '', pathUrl: '', area: ' 《國內》', category: ' 地方政府/高雄市', title: '國小老師被小四學生戳肛門，反被逼離職', rarity: ' 一般', prefix: ' ', suffix: ' 教育與文化<br>法治與行政' },
    { date: '2026-06-06', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府/地方政府', title: '不是淹水，是積水！', rarity: ' 一般', prefix: ' 自訂義/護航/雙標', suffix: ' 環境與基礎建設' },
    { date: '2026-05-14', path: '', pathUrl: '', area: ' 《國內》', category: ' 中央政府/地方政府', title: '經濟部能源署、水利署、環境部、高雄市政府，網址被駭，變外送茶網頁！', rarity: ' 一般', prefix: ' 數位中介法', suffix: ' 法治與行政<br>自導自演' },
    { date: '2026-07-24', path: '⛨', pathUrl: 'https://swallow-234.github.io/swallow_234/%E3%80%8A%E8%81%96%E5%85%89%E6%95%99%E6%95%99%E4%B8%BB%E3%80%8B/%E5%80%89%E5%BA%AB/%E6%B8%85%E5%96%AE/%E5%B0%88%E6%A1%88%E6%95%B4%E7%90%86-%E8%90%8A%E5%85%8B%E5%A4%9A%E5%B7%B4%E8%83%BA.html', area: ' 《鼠鼠戰團》<br>《國內外》', category: ' 《專案整理》<br>進出口', title: ' 萊克多巴胺', rarity: ' 重度', prefix: ' 動動鼠', suffix: ' 社會與民生<br>食安<br>豬肉<br>牛肉' },
    { date: '日期', path: '章節/輿圖', pathUrl: 'https://swallow-234.github.io/swallow_234/%E5%85%AC%E4%BD%88%E6%AC%84', area: '系列勢力', category: '主題 ', title: '標題 ', rarity: '稀有度 ', prefix: '前綴 ', suffix: '後綴 ' }
];
const workData2 = [...workData].sort((a, b) => {
        return b.date.localeCompare(a.date);
    });