// sidebar.js
const sidebarContent = `
<a href="https://swallow-234.github.io/swallow_234/%E5%85%AC%E4%BD%88%E6%AC%84">首頁</a>
    <h1 style="text-align: center;">《專輯收藏》</h1>
<ul><li><a onclick="changeIframe('音樂收藏-範本.html')">單曲收藏</a></li>
     <li><a onclick="changeIframe('../《青丘茶館》/音樂專輯收藏.html')">專輯收藏</a></li>
<hr class="b005">
<h3 style="text-align: center;">《導師塔》</h3><hr class="a001">
    <li><a href="https://www.youtube.com/@Hinomu">Hinomu</a></li>
    <li><a href="https://www.youtube.com/@MilgramOfficial">MILGRAM -ミルグラム-</a></li>
    <li><a href="https://www.youtube.com/@WindmusicTw/playlists">風潮音樂 Wind Music</a></li>
    <li><a href="https://www.youtube.com/channel/UCNvmLRL3gdL1SH0tmCMAm5Q">萌樂 ‧ Meng Yue ᴴᴰ</a></li>
    <li><a href="https://www.youtube.com/@-Kirasa/videos">アリス ‧ Kirasa</a></li>
    <li><a href="https://www.youtube.com/@ShiaMusic-hm9zr/videos">希亞音樂Shia Fantasy Story Music</a></li>
    <li><a href="https://www.youtube.com/channel/UCSeJA6az0GrNM4_-pl3HQSQ/videos">Adrian von Ziegler</a></li>
    <li><a href="https://www.youtube.com/@warriorsbattlejukebox1840/playlists">Warriors Battle Jukebox</a></li>
    <li><a href="https://www.youtube.com/@NGC314">NGC314 NGC314</a></li>
    <li><a href="https://www.youtube.com/@TamusicJp">TAMUSIC [Touhou CLASSIC]</a></li>
    <li><a href="https://www.youtube.com/@UnderGroundK/playlists">UnderGround</a></li>
    <li><a href="https://www.youtube.com/@izayoisakuya1766/playlists">Izayoi Sakuya</a></li>
    <li><a href="https://www.youtube.com/@%E3%81%B5%E3%81%83%E3%81%99">ふぃす</a></li>
    <li><a href="https://www.youtube.com/@touhoumusic7055/playlists">東方Touhou Music</a></li>
    <li><a href="https://www.youtube.com/@jagmo2023/playlists">JAGMO</a></li>
    <li><a href="https://www.youtube.com/@katukunazawa5121/videos">katukunazawa</a></li>
    <li><a href="https://www.youtube.com/@TheLittlePagoda">The Little Pagoda</a></li>
    <li><a href="https://www.youtube.com/@prismriverorchestra440">Prismriver Orchestra</a></li>
    <li><a href="https://www.youtube.com/@colourless_c/videos">무색양초</a></li>
    <li><a href="https://www.youtube.com/@Terraaa">Terra</a></li>
    <li><a href="https://www.youtube.com/@crystalmemories865/videos">Crystal Memories</a></li>
    <li><a href="https://www.youtube.com/@SkuddeOuo/playlists">SkuddeOuo</a></li>
    <li><a href="https://www.youtube.com/@yuuheitube2011/playlists">幽閉サテライト・少女フラクタル・幽閉カタルシス 公式チャンネル</a></li>
    <li><a href="https://www.youtube.com/@EpreTrollII/playlists">EpreTroll II</a></li>
    <li><a href="https://www.youtube.com/@ssbbmaster/playlists">ssbbmaster</a></li>
    <li><a href="https://www.youtube.com/@LowlandsBlossom/playlists">Lowlands Blossom</a></li>
    <li><a href="https://www.youtube.com/@crystalmemories865/playlists">Crystal Memories</a></li>
    <li><a href="https://www.youtube.com/@BzB003/playlists">BzB 003</a></li>
    <li><a href="https://www.youtube.com/c/Quwanti1">Quwanti</a></li>
    <li><a href="https://www.youtube.com/@mayumin445/playlists">Mayumi Sugihara</a></li>
    <li><a href="https://www.youtube.com/@melodiastis6876/playlists">Melodiastis</a></li>
    <li><a href="https://www.youtube.com/@Renko/playlists">Renkoレンコ</a></li>
    <li><a href="https://www.youtube.com/@incompetech_kmac/playlists">Kevin MacLeod</a></li>
    <li><a href="https://www.youtube.com/@yunosuke23/playlists">雄之助/Yunosuke</a></li>
    <li><a href="https://www.youtube.com/@DeadMusicFC/playlists">Naharu</a></li>
    <li><a href="https://www.youtube.com/@-Rutanbuna/playlists">蘆棠布奈【TMG_Not_Company】</a></li>
    <li><a href="https://www.youtube.com/@Xefox/playlists">Xefox Music</a></li>
    <li><a href="https://www.youtube.com/@warnermusicjapan/playlists">Warner Music Japan</a></li>
    <li><a href="https://www.youtube.com/@VESPERBELL/playlists">VESPERBELL</a></li>
    <li><a href="https://www.youtube.com/@tfkofficial/playlists">Thousand Foot Krutch</a></li>
    <li><a href="https://www.youtube.com/@ThoughtsOfASlayer/playlists">Thoughts of a Slayer</a></li>
    <li><a href="https://www.youtube.com/@TheFatRat/playlists">TheFatRat</a></li>
    <li><a href="https://www.youtube.com/@TBMOfficial/playlists">The Birthday Massacre</a></li>
    <li><a href="https://www.youtube.com/@SuicideSheeep/playlists">SuicideSheeep</a></li>
    <li><a href="https://www.youtube.com/@TaiGekTou/videos">TaiGekTou</a></li>
    <li><a href="https://www.youtube.com/@ThePrimeCronus/videos">ThePrimeCronus</a></li>
    <li><a href="https://www.youtube.com/@bluepandoli/playlists">Blue Pandoli</a></li>
    <li><a href="https://www.youtube.com/@mo2bluearchive/videos">MO2</a></li>
    <li><a href="https://www.youtube.com/@ruraaraaru/playlists">R2乗</a></li>
    <li><a href="https://www.youtube.com/@ChillCartoonVibesLAB/videos">Chill Cartoon Vibes</a></li>
    <li><a href="https://www.youtube.com/@TastyNetwork/playlists">Tasty</a></li>
    <li><a href="https://www.youtube.com/@TohoPiano/videos">TOUHOU PIANO</a></li>
    <li><a href="https://www.youtube.com/@SubZero90EpicMusic/playlists">SubZero90EpicMusic</a></li>
    <li><a href="https://www.youtube.com/@THECHAINSMOKERS/playlists">The Chainsmokers</a></li>
    <li><a href="https://www.youtube.com/@snowdancemusicchannel632/videos">SnowDance MusicChannel</a></li>
    <li><a href="https://www.youtube.com/@Sieudiver/playlists">Sieudiver</a></li>
    <li><a href="https://www.youtube.com/@Shujiki/videos">Shujiki</a></li>
    <li><a href="https://www.youtube.com/@lisaSMEJ/videos">LiSA Official YouTube</a></li>
    <li><a href="https://www.youtube.com/channel/UCU5jTBj3ae-kAsdHj3WM5Yw">Shiratori Kotori (CV:Ayasa Ito)</a></li>
    <li><a href="https://www.youtube.com/@JFlaMusic/videos">JFlaMusic</a></li>
    <li><a href="https://www.youtube.com/@SanuksananNightcore/videos">Sanuksanan Nightcore</a></li>
    <li><a href="https://www.youtube.com/@Shininghorse8/videos">S</a></li>
    <li><a href="https://www.youtube.com/@RobertChen/videos">Robert Chen</a></li>
    <li><a href="https://www.youtube.com/@Rainych/videos">Rainych Ran</a></li>
    <li><a href="https://www.youtube.com/@OneRepublic/videos">OneRepublic</a></li>
    <li><a href="https://www.youtube.com/@nusmax/videos">nusmax</a></li>
    <li><a href="https://www.youtube.com/@Noodles3996/playlists">Noodles</a></li>
    <li><a href="https://www.youtube.com/@nightwishimaginaerum/playlists">Nightwish Imaginaerum</a></li>
    <li><a href="https://www.youtube.com/@nightwish/videos">Nightwish</a></li>
    <li><a href="https://www.youtube.com/@Nakasako/videos">中迫酒菜 - Nakasako Sakana</a></li>
    <li><a href="https://www.youtube.com/@mykoolofficial/videos">MYKOOL</a></li>
    <li><a href="https://www.youtube.com/@mwamjapan8665/featured">mwamjapan</a></li>
    <li><a href="https://www.youtube.com/@ColombiaGamerHD/videos">MusicFuriax</a></li>
    <li><a href="https://www.youtube.com/@MontageRock/videos">MontageRock</a></li>
    <li><a href="https://www.youtube.com/@MitchieM/videos">Mitchie M</a></li>
    <li><a href="https://www.youtube.com/@MiddleAgesMusic/videos">Middle Ages</a></li>
    <li><a href="https://www.youtube.com/channel/UCGZRvIWrW3n2ln5OJmx6UBg">Melodic Taste</a></li>
    <li><a href="https://www.youtube.com/@Maroon5/videos">Maroon 5</a></li>
    <li><a href="https://www.youtube.com/@Manafest/featured">Manafest</a></li>
    <li><a href="https://www.youtube.com/channel/UC0-8T95B-JheVF3-I3Yeeew">Macro Stereo / マクロステレオ</a></li>
    <li><a href="https://www.youtube.com/c/machineheart">MACHINEHEART</a></li>
    <li><a href="https://www.youtube.com/@m4sonic/playlists">M4SONIC</a></li>
    <li><a href="https://www.youtube.com/@LinkinPark/videos">Linkin Park</a></li>
    <li><a href="https://www.youtube.com/channel/UCyC_4jvPzLiSkJkLIkA7B8g">Lindsey Stirling</a></li>
    <li><a href="https://www.youtube.com/channel/UC7rqz5As19qYWl2Rc4z-iig">Lefty Hand Cream【Official】</a></li>
    <li><a href="https://www.youtube.com/c/kavvsona/featured">LeagueOfMusic</a></li>
    <li><a href="https://www.youtube.com/@LadyGaga/playlists">Lady Gaga</a></li>
    <li><a href="https://www.youtube.com/c/Krewella">Krewella</a></li>
    <li><a href="https://www.youtube.com/c/KohMei">KohMei</a></li>
    <li><a href="https://www.youtube.com/c/Hujikoman">kobasolo</a></li>
    <li><a href="https://www.youtube.com/@kkcwkoh/featured">kkcwkoh</a></li>
    <li><a href="https://www.youtube.com/user/kingrecords">KING RECORDS</a></li>
    <li><a href="https://www.youtube.com/c/KenshiYonezuHACHI">Kenshi Yonezu 米津玄師</a></li>
    <li><a href="https://www.youtube.com/@katukunazawa5121/videos">katukunazawa</a></li>
    <li><a href="https://www.youtube.com/@KouOgata/playlists">k-waves LAB / 樹衣うい</a></li>
    <li><a href="https://www.youtube.com/@JoelNielsenMusic/playlists">JoelNielsenMusic</a></li>
    <li><a href="https://www.youtube.com/@joehisaishiofficial9777/playlists">Joe Hisaishi Official</a></li>
    <li><a href="https://www.youtube.com/c/hinatubechannel">HINA</a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
</ul>
    <hr class="a001">
`;

// 自動填充到頁面中
document.addEventListener("DOMContentLoaded", function() {
    const nav = document.getElementById('mySidenav');
    if (nav) {
        nav.innerHTML = sidebarContent;
    }
});